#pragma once
#define UNICODE

#ifndef DEFINES_H
#define DEFINES_H

#define WINDOW_CLASS L"The Wilds"
#define WINDOW_NAME L"Wilds"

#define GRAVITY 9.8
#define WinHWND HWND

#define SPOTLIGHT 1
#define DIRECTLIGHT 2
#define POINTLIGHT 3
typedef long Vertextype;


enum PrimType
{
	NULL_TYPE,POIST_LIST,TRANGLE_LIST,TRANGLE_STRIP,TRANGLE_FAN,LINE_STRIP,LINE_LIST,
};

enum RenderState
{
	CULL_NONE,
	CULL_CW,
	CULL_CCW,
	DEPTH_NONE,
	DEPTH_READONLY,
	DEPTH_READWRITE,
	SHADE_POINTS,
	SHADE_SOIDTRI,
	SHADE_WIRETR,
	SHADE_WIREPOLY,
	TRANSPARENCY_NONE,
	TRANSPARENCY_ENABLE
};

enum  TransState
{
	TRANS_ZERO=1,
	TRANS_ONE,
	TRANS_SRCCOLOR,
	TRANS_INVSRCOLOR,
	TRANS_SRCALPHA,
	TRANS_INVSRCALPHA,
	TRANS_DSTALPHA,
	TRANS_INVDSTALPHA,
	TRANSA_SRCALPHASAT,
	TRANS_BOTHSRCALPHA,
	TRANS_INVBOTHSRCALPHA,
	TRANS_BLENDFACTOR,
	TRANS_INVBLENDFACTOR
};
enum TextureState {
	MIN_FILTER,
	MAG_FILTER,
	MIP_FILTER
};

enum FilterType
{
	POINT_TYPE,
	LINEAR_TYPE,
	ANISOTROPIC_TYPE
};
#endif
