#pragma once

#ifndef DEFINES_H
#define DEFINES_H


#define UGP_INVALID -1
#define UGP_OK 1
#define UGP_FAIL 0


#define GRAVITY 9.8
//#define WinHWND HWND

#define SPOTLIGHT 1
#define DIRECTLIGHT 2
#define POINTLIGHT 3
typedef long Vertextype;


enum PrimType{
	NULL_TYPE,
	POIST_LIST,
	LINE_STRIP,LINE_LIST,
	TRANGLE_LIST,TRANGLE_STRIP,TRANGLE_FAN
};

/*
#define UGPCOLOR_ARGB(a,r,g,b) ((unsigned long))((((a)&0xff)<24) | \
								(((r)&0xff)<<16) | (((g)&0xff)<<8) |\
								(((b)&0xff)))
*/

enum RenderState{
	CULL_NONE,
	CULL_CW,//ÌÞ³ýË³Ê±ÕëµÄ¶¥µã
	CULL_CCW,//ÌÞ³ýÄæÊ±ÕëµÄ¶¥µã
	DEPTH_NONE,
	DEPTH_READONLY,
	DEPTH_READWRITE,
	SHADE_POINTS,
	SHADE_SOIDTRI,
	SHADE_WIRETR,
	SHADE_WIREPOLY,
	TRANSPARENCY_NONE,
	TRANSPARENCY_ENABLE
};

enum  TransState{
	TRANS_ZERO=1,
	TRANS_ONE,
	TRANS_SRCCOLOR,
	TRANS_INVSRCOLOR,
	TRANS_SRCALPHA,
	TRANS_INVSRCALPHA,
	TRANS_DSTALPHA,
	TRANS_INVDSTALPHA,
	TRANSA_SRCALPHASAT,
	TRANS_BOTHSRCALPHA,
	TRANS_INVBOTHSRCALPHA,
	TRANS_BLENDFACTOR,
	TRANS_INVBLENDFACTOR
};
enum TextureState {
	MIN_FILTER,
	MAG_FILTER,
	MIP_FILTER
};

enum FilterType
{
	POINT_TYPE,
	LINEAR_TYPE,
	ANISOTROPIC_TYPE
};
#endif
